name: OnComment
on: 
  issue_comment:
    types: [created]

jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: ${{ github.event.issue.pull_request && github.event.comment.body == 'run'}}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo GITHUB EVENT AUTHOR IS: ${{ github.event.issue_comment.author_association }} nd EVENT ISSUE NUMBER ${{ github.event.issue.author_association }}
        env:
          NUMBER: ${{ github.event.issue.number }}
          NAME: ${{ github.event.issue.user.login }}
